mavenproject3/src/main/java/com/mycompany/mavenproject3/model/Direktor.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.mavenproject3.model;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 *
 * @author Grupa1
 */
@Entity
@Table(name="DIREKTOR")
public class Direktor {
     @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    private long id;
    
    @OneToOne
     @JoinColumn(name="korisnik_id")
    private Korisnik korisnik;

    public Direktor() {
    }

    public Direktor(long id) {
        this.id = id;
    }

    public Direktor(Korisnik korisnik) {
        this.korisnik = korisnik;
    }

    public Direktor(long id, Korisnik korisnik) {
        this.id = id;
        this.korisnik = korisnik;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public Korisnik getKorisnik() {
        return korisnik;
    }

    public void setKorisnik(Korisnik korisnik) {
        this.korisnik = korisnik;
    }

    @Override
    public String toString() {
        return "Direktor{" + "id=" + id + ", korisnik=" + korisnik + '}';
    }

    
}

mavenproject3/src/main/java/com/mycompany/mavenproject3/model/Roditelj.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.mavenproject3.model;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 *
 * @author Grupa1
 */
@Entity
@Table(name = "RODITELJ")
public class Roditelj {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id;

    @OneToOne
    @JoinColumn(name = "korisnik_id")
    private Korisnik korisnik;

    @ManyToMany
    @JoinTable(
            name = "ROD_UCE",
            joinColumns
            = @JoinColumn(name = "RODITELJ_ID", referencedColumnName = "ID"),
            inverseJoinColumns
            = @JoinColumn(name = "UCENIK_ID", referencedColumnName = "ID"))
    private Set <Ucenik> ucenici = new HashSet<>();

    public Roditelj() {
    }

    public Roditelj(long id) {
        this.id = id;
    }

    public Roditelj(long id, Korisnik korisnik) {
        this.id = id;
        this.korisnik = korisnik;
    }


    
    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public Korisnik getKorisnik() {
        return korisnik;
    }

    public void setKorisnik(Korisnik korisnik) {
        this.korisnik = korisnik;
    }

    public Set<Ucenik> getUcenici() {
        return ucenici;
    }

    public void setUcenici(Set<Ucenik> ucenici) {
        this.ucenici = ucenici;
    }

    @Override
    public String toString() {
        return "Roditelj{" + "id=" + id + ", korisnik=" + korisnik + ", ucenici=" + ucenici + '}';
    }

   
   

}

mavenproject3/src/main/java/com/mycompany/mavenproject3/model/UcenikTest.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.mavenproject3.model;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

 @Entity
 @Table(name="UCENIK")
public class UcenikTest {
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    private long id;
    
    @ManyToOne 
    @JoinColumn(name="godina_id")
    private GodinaTest godina;

    private String Ime;

    private String Prezime;

    public UcenikTest() {
    }

    public UcenikTest(String Ime, String Prezime) {
        this.Ime = Ime;
        this.Prezime = Prezime;
    }

    public UcenikTest(GodinaTest godina, String Ime, String Prezime) {
        this.godina = godina;
        this.Ime = Ime;
        this.Prezime = Prezime;
    }

   

    
    
    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getIme() {
        return Ime;
    }

    public void setIme(String Ime) {
        this.Ime = Ime;
    }

    public String getPrezime() {
        return Prezime;
    }

    public void setPrezime(String Prezime) {
        this.Prezime = Prezime;
    }

    public GodinaTest getGodina() {
        return godina;
    }

    public void setGodina(GodinaTest godina) {
        this.godina = godina;
    }

    @Override
    public String toString() {
        return "Ucenik{" + "id=" + id + ", godina=" + godina + ", Ime=" + Ime + ", Prezime=" + Prezime + '}';
    }

   
   

   

    
    

    
    
    
}

mavenproject3/src/main/java/com/mycompany/mavenproject3/model/Ucitelj.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.mavenproject3.model;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 *
 * @author Grupa1
 */
@Entity
@Table(name = "UCITELJ")
public class Ucitelj {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id;

    @OneToOne
    @JoinColumn(name = "korisnik_id")
    private Korisnik korisnik;
    
     @OneToOne
    @JoinColumn(name = "odeljenje_id")
    private Odeljenje odeljenje;
    

    public Ucitelj() {
    }

    public Ucitelj(long id) {
        this.id = id;
    }

    public Ucitelj(Korisnik korisnik) {
        this.korisnik = korisnik;
    }

    public Ucitelj(long id, Korisnik korisnik) {
        this.id = id;
        this.korisnik = korisnik;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public Korisnik getKorisnik() {
        return korisnik;
    }

    public void setKorisnik(Korisnik korisnik) {
        this.korisnik = korisnik;
    }

    @Override
    public String toString() {
        return "Ucitelj{" + "id=" + id + ", korisnik=" + korisnik + '}';
    }

    
}

mavenproject3/src/main/webapp/WEB-INF/view/allUcenik.jsp
<%-- 
    Document   : SviUcenici
    Created on : Mar 15, 2019, 11:53:59 AM
    Author     : Grupa1
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>

<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
    "http://www.w3.org/TR/html4/loose.dtd">

<f:view>
    <html>
        <head>
            <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
            <title>JSP Page</title>
        </head>
        <body>
            <h1><h:outputText value="Hello World!"/></h1>


            <table class="table table-hover">

                <thead>
                    <tr>
                        <th><b>Ime</b></th>
                        <th><b>Prezime</b></th>

                    </tr>
                </thead>
                <tbody>
                    <c:forEach items="${list}" var="lou">
                        <tr>

                            <td><c:out value="${lou.ime}"></c:out></td>
                            <td><c:out value="${lou.prezime}"></c:out></td>
                            <td><c:out value="${lou.godina}"></c:out></td>

                                <td>
                                    <a href="/ucenik/${lou.id}/editUcenik">
                                    <button type="submit" class="btn btn-primary">Edit User</button>
                                </a>
                            </td>
                            <td>
                                <a href="/ucenik/${lou.id}/delete">
                                    <button type="submit" class="btn btn-primary">Delete User</button>
                                </a>
                            </td>
                        </tr>

                    </c:forEach>
                </tbody>
            </table>
        </body>


    </html>
</f:view>

mavenproject3/src/main/webapp/WEB-INF/view/direktor.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>

<html>
    <head>
        <title>Strana za direktora</title>
        <link href="/webjars/bootstrap/4.3.0/css/bootstrap.min.css"
              rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="/style.css">
    </head>    
    <body>
        <div id="wrapper">
            <ul class="tabs">
                <li><a href="#" name="tab6">Statistika uspesnosti po odeljenjima</a></li>
                <li><a href="#" name="tab7">Statistika uspesnosti po predmetima</a></li>
            </ul>
            <div id="content">
                <div id="tab6">
                    <div id="biranjeOdeljenja">
                        <h3>Izaberi odeljenje</h3>
                        <select class="izborOdeljenja">
                            <option>1</option>
                            <option>2</option>
                            <option>3</option>
                            <option>4</option>
                            <option>5</option>
                        </select>
                    </div>
                </div>
                <div id="tab7">
                    <div id="biranjePredmeta">
                        <h2>Izaberi predmet</h2>
                        <select class="izborPredmeta">
                            <option>1</option>
                            <option>2</option>
                            <option>3</option>
                            <option>4</option>
                            <option>5</option>
                        </select>
                    </div>
                </div>
            </div>
            <script src="/webjars/jquery/3.2.0/jquery.min.js"></script>
            <script src="/webjars/bootstrap/4.3.0/js/bootstrap.min.js"></script>
            <script src="http://code.jquery.com/jquery-1.7.2.min.js"></script>
            <script src="/design.js"></script>
        </div>
    </body>
</html>

mavenproject3/src/main/webapp/WEB-INF/view/editUcenik.jsp
<%-- 
    Document   : editUcenik
    Created on : Mar 19, 2019, 9:56:02 AM
    Author     : Grupa1
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>

<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
    "http://www.w3.org/TR/html4/loose.dtd">

<f:view>
    <html>
        <head>
            <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
            <title>JSP Page</title>
        </head>
        <body>
            <h1><h:outputText value="Hello World!"/></h1>
            <div class="container">
                <div>

                    <table>
                        <tr></tr>
                        <td><b>Id</b></td>
                        <td>${ucenik.id}</td>
                        <tr>
                            <td><b>Ime</b></td>
                            <td>"${ucenik.ime}"</td>
                        </tr>
                        <tr>
                            <td><b>Prezime</b></td>
                            <td>"${ucenik.prezime}"</td>
                        </tr>
                        <tr>
                            <td><b>Godina</b></td>
                            <td>${ucenik.godina}</td>
                        </tr>
                    </table>
                </div>
                <form action='/ucenik/update' method='post'>



                    <table class='table table-hover table-responsive table-bordered'>

                        <tr>
                            <td><b>Ime</b></td>
                            <td><input type='text' name='ime' class='form-control' value="${ucenik.ime}" /></td>
                        </tr>

                        <tr>
                            <td><b>Prezime</b></td>
                            <td><input type='text' name='prezime' class='form-control' value="${ucenik.prezime}" /></td>
                        </tr>

                        <label>Godina: </label> 

                        <select name="godinaId">
                            <c:forEach items="${listGodina}" var="lg">
                                <option  value="<c:out value="${lg.id}"></c:out>">${lg.godina}</option>
                            </c:forEach>
                        </select>

                        <input type="hidden" id='id' rows='5' class='form-control' name='id' value="${ucenik.id}" />
                        <tr>
                            <td></td>
                            <td>
                                <button type="submit" class="btn btn-primary">Update Ucenik Information</button>
                            </td>
                        </tr>

                    </table>
                </form>


            </div>
        </body>
    </html>
</f:view>

mavenproject3/src/main/webapp/WEB-INF/view/index.jsp
<%-- 
    Document   : index
    Created on : Mar 14, 2019, 10:56:34 AM
    Author     : Grupa1
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>

<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
    "http://www.w3.org/TR/html4/loose.dtd">

<f:view>
    <html>
        <head>
            <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
            <title>JSP Page</title>
        </head>
        <body>
            <h1><h:outputText value="Hello World!"/></h1>
            <form name="send" action="/ucenik/dodaj" method="POST"> 
                <input type="text" name="ime"> 
                <input type="text" name="prezime"> 
                <label>Godina: </label> 
                
                               <select name="godinaId">
                    <c:forEach items="${listGodina}" var="lg">
                        <option  value="<c:out value="${lg.id}"></c:out>">${lg.godina}</option>
                    </c:forEach>
                </select>
                
                <input type="submit" value="Submit"> 
            </form>
            
            
            
<br>

        </body>
    </html>
</f:view>

mavenproject3/src/main/webapp/WEB-INF/view/komunikaciija.jsp
<%-- 
    Document   : komunikaciija
    Created on : 08-Mar-2019, 09:22:25
    Author     : Grupa1
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>

<%@taglib prefix="f" uri="http://java.sun.com/jsf/core"%>
<%@taglib prefix="h" uri="http://java.sun.com/jsf/html"%>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
    "http://www.w3.org/TR/html4/loose.dtd">

<f:view>
    <html>
        <head>
            <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
            <title>JSP Page</title>
        </head>
        <body>
            <h1><h:outputText value="Hello World!"/></h1>
        </body>
    </html>
</f:view>

mavenproject3/src/main/webapp/WEB-INF/view/roditelj.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>

<html>
    <head>
        <title>Strana za roditelje</title>
        <link href="/webjars/bootstrap/4.3.0/css/bootstrap.min.css"
              rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="/style.css">

    </head>
    <body>
        <div id="wrapper">

            <div>
                <ul id="tabs">
                    <li><a href="#" name="tab1">Pogledaj ocene</a></li>
                    <li><a href="#" name="tab2">Pogledaj izostanke</a></li>
                    <li><a href="#" name="tab3">Zakazivanja</a></li>
                    <li><a href="#" name="tab4">Poruke</a></li>
                    <li><a href="#" name="tab5">Obavestenja</a></li>    
                </ul>
            </div>

            <div id="content"> 
                <div id="tab1">
                    <div class="container" id="dodavanjeKorisnika">
                        <form>
                            <div class="form-option">
                                <label for="exampleInputOption1">Izaberite ulogu:</label>
                                <select type="option" class="option-control" id="exampleInputOption1">
                                    <option>Administrator</option>
                                    <option>Direktor</option>
                                    <option>Nastavnik</option>
                                    <option>Roditelj</option>
                                    <option>Ucenik</option>
                                </select>
                                <br><br>
                            </div>

                            <div class="form-group">
                                <label for="exampleInputEmail1">Enter First Name:</label> <input
                                    type="email" class="form-control" id="ime"
                                    aria-describedby="emailHelp" placeholder="New First Name">
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Enter Last Name:</label> <input
                                    type="email" class="form-control" id="prezime"
                                    aria-describedby="emailHelp" placeholder="New Last Name">
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Enter new Email address:</label> <input
                                    type="email" class="form-control" id="exampleInputEmail1"
                                    aria-describedby="emailHelp" placeholder="New email">
                            </div>
                            <div class="form-group">
                                <label for="exampleInputPassword1">Enter new Password:</label> <input
                                    type="password" class="form-control" id="exampleInputPassword1"
                                    placeholder="New Password">
                            </div>
                            <div class="form-group">
                                <label for="exampleInputPassword1">Repeat Password:</label> <input
                                    type="password" class="form-control" id="exampleInputPassword1"
                                    placeholder="Repeat New Password">
                            </div>
                            <br>
                            <hr>
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </form>
                    </div>
                </div>
            </div>

            <script src="/webjars/jquery/3.2.0/jquery.min.js"></script>
            <script src="/webjars/bootstrap/4.3.0/js/bootstrap.min.js"></script>
            <script src="http://code.jquery.com/jquery-1.7.2.min.js"></script>
            <script src="/design.js"></script>

        </div>
    </body>
</html>

mavenproject3/src/main/webapp/WEB-INF/view/ucitelj.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>

<html>
    <head>
        <title>Strana za ucitelje</title>
        <link href="/webjars/bootstrap/4.3.0/css/bootstrap.min.css"
              rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="/style.css">

    </head>
    <body>
        <div id="wrapper">

            <div>
                <ul id="tabs">
                    <li><a href="#" name="tab1">Odeljenje</a></li>
                    <li><a href="#" name="tab2">Ocene</a></li>
                    <li><a href="#" name="tab3">Raspored casova</a></li>
                    <li><a href="#" name="tab4">Zahtevi</a></li>
                    <li><a href="#" name="tab5">Poruke</a></li>
                    <li><a href="#" name="tab6">Obavestenja</a></li>    
                </ul>
            </div>

            <script src="/webjars/jquery/3.2.0/jquery.min.js"></script>
            <script src="/webjars/bootstrap/4.3.0/js/bootstrap.min.js"></script>
            <script src="http://code.jquery.com/jquery-1.7.2.min.js"></script>
            <script src="/design.js"></script>

        </div>

    </body>
</html>